[package]
name = "sd-formatter"
version = "0.1.0"
edition = "2021"

[dependencies]
utf16string = "0.2.0"

[dependencies.winapi]
version = "0.3.9"
features = ["setupapi", "handleapi", "errhandlingapi", "winerror", "winioctl", "devpkey"]
